// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { getSupabaseBrowserApiKey } from '@/lib/supabase-browser-key';
import { assertSupabaseAnonMatchesUrl } from '@/lib/supabase-project-match';

const SUPABASE_URL = String(import.meta.env.VITE_SUPABASE_URL ?? "").trim();
const SUPABASE_KEY = getSupabaseBrowserApiKey();

if (!SUPABASE_URL) {
  throw new Error(
    "[Supabase] Defina VITE_SUPABASE_URL no .env (Dashboard → Settings → API → Project URL).",
  );
}
if (!SUPABASE_KEY) {
  throw new Error(
    "[Supabase] Defina VITE_SUPABASE_PUBLISHABLE_KEY ou VITE_SUPABASE_ANON_KEY no .env — mesma página (API), mesmo projeto da URL. Valores vazios geram este erro.",
  );
}

assertSupabaseAnonMatchesUrl(SUPABASE_URL, SUPABASE_KEY);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});